language: node_js
node_js: "13.8.0"
os:
  - linux
  - windows

addons:
  chrome: stable
  apt:
    packages:
      - xvfb

services:
  - xvfb

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sleep 3; fi

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y install libxtst-dev libpng++-dev; fi

install:
  - npm install robotjs --target=7.1.12
  - npm install
  - echo "npm test temporarily disabled"

script: true

jobs:
  include:
    - stage: test
      if: os = linux
      name: "Linting Checks"
      script: npm run lint
    - stage: test
      if: os = linux
      script: npm run test
      name: "Running E2E Tests"
    - stage: build
      if: (os = linux) OR (os = windows)
      name: "Building"
      script: npm run build
    - stage: deploy
      if: (branch = master) AND ((os = windows) OR (os = linux))
      script: npm run release
      name: "Deploying Release"
