language: node_js
node_js: "13.8.0"
os:
  - linux
  - windows

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sleep 3; fi

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y install libxtst-dev libpng++-dev

install:
  - npm install robotjs --target=7.1.12
  - npm install

jobs:
  include:
    - stage: test
      name: "Linting Checks"
      script: npm run lint
    - script: npm run test
      name: "Running E2E Tests"
    - stage: build
      name: "Building"
      script: npm run build
    - stage: deploy
      if: branch = master
      script: npm run release
      name: "Deploying Release"
