language: node_js
node_js: "13.8.0"
os: windows

install:
  - npm install robotjs --target=7.1.12
  - npm install

branches:
  only:
    - master

jobs:
  include:
    - stage: test
      name: "Linting Checks"
      script: npm run lint
    - script: npm run test
      name: "Running E2E Tests"
    - stage: build
      name: "Building"
      script: npm run build
    - stage: deploy
      script: npm run release
      name: "Deploying Release"
