# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # linux
  linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Decrypt ENV
        run: |
          pwd
          ./.github/decrypt.sh
          ls -la
        env:
          ENV_SECRET: ${{ secrets.ENV_SECRET }}

      # Setup Node.JS
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      # Setup linux environment for E2E testing
      - name: Install linux packages
        run: sudo apt-get -y install libxtst-dev libpng++-dev libcairo2-dev libpango1.0-dev libgif-dev

      # Install RobotJS
      - name: Install Natives
        run: npm install robotjs canvas --target=9.2.0

      # Install all remaining dependencies
      - name: Install Remaining Dependencies
        run: npm i

      - name: Building
        run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      # Cleanup
      - name: Cleanup xvfb pidx
        uses: bcomnes/cleanup-xvfb@v1
  # windows
  windows:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Decrypt ENV
        run: |
          ./.github/decrypt.cmd
          dir
        env:
          ENV_SECRET: ${{ secrets.ENV_SECRET }}

      # Setup Node.JS
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Configure node-gyp
        run: node-gyp configure

      - name: Install GTK Dependencies
        run: |
          Invoke-WebRequest "http://ftp.gnome.org/pub/GNOME/binaries/win64/gtk+/2.22/gtk+-bundle_2.22.1-20101229_win64.zip" -OutFile "gtk.zip"
          Expand-Archive gtk.zip -DestinationPath "C:\GTK"

      # Install Canvas
      - name: Install node-canvas
        run: npm install canvas --target=9.2.0

      # Install RobotJS
      - name: Install Natives
        run: npm install robotjs --target=9.2.0

      # Install all remaining dependencies
      - name: Install Remaining Dependencies
        run: npm i

      - name: Building
        run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
