# This is a basic workflow to help you get started with Actions

name: Testing

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # use chrome driver
    - uses: nanasess/setup-chromedriver@master
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Setup Node.JS
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '13.x'

    # Setup linux enviroment for E2E testing
    - name: Install linux packages
      run: sudo apt-get -y install libxtst-dev libpng++-dev

    # Install RobotJS
    - name: Install Natives
      run: npm install robotjs --target=7.1.12
    
    # Install all remaining dependencies
    - name: Install Dependencies
      run: npm ci
    
    # Run linting checks
    - name: Linting Check
      run: npm run lint
    
    # Run E2E test
    - name: Run Headless E2E Test
      timeout-minutes: 5
      run: |
        export DISPLAY=:99.0
        xvfb-run --auto-servernum npm test
      env:
        CI: true
    
    # Cleanup
    - name: Cleanup xvfb pidx
      uses: bcomnes/cleanup-xvfb@v1
